export const copy = {
  common: {
    loadError: 'Unable to load protocol data.',
    retry: 'Retry connection',
    sync: 'Run sync',
    syncing: 'Syncing...',
    syncComplete: 'Sync complete. Protocol data is up to date.',
    syncFailed: 'Sync failed.',
    notAvailable: 'N/A',
    notSynced: 'Not synced yet',
    unknownTime: 'Unknown time',
    noErrorSummary: 'No error summary',
  },
  auth: {
    readOnly: 'Read-only',
    eyebrow: 'AAVE V3 / ETHEREUM / INDEXED INTELLIGENCE',
    headline: 'Follow the liquidity pulse.',
    description: 'Turn The Graph\'s on-chain index into traceable, auditable, reproducible DeFi intelligence.',
    snapshotHistory: 'Historical snapshots',
    reserveMarkets: 'Reserve markets',
    chainWrites: 'On-chain writes',
    secureWorkspace: 'Secure workspace',
    signInTitle: 'Enter the monitoring console',
    signInDescription: 'Connect to the local read-only protocol data space.',
    username: 'Username',
    password: 'Password',
    captcha: 'Captcha',
    refreshCaptcha: 'Refresh captcha',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalidCredentials: 'Invalid credentials or captcha.',
    captchaLoadError: 'Unable to load captcha.',
    completeFields: 'Enter your username, password, and captcha.',
    demoAccount: 'Local demo account:',
  },
  dashboard: {
    navigation: 'Primary navigation',
    overview: 'Overview',
    overviewHint: 'Protocol pulse',
    reserves: 'Reserves',
    reservesHint: 'Market directory',
    syncRuns: 'Sync runs',
    syncRunsHint: 'Data pipeline',
    ethereumMainnet: 'Ethereum Mainnet',
    protocolNetwork: 'AAVE V3 / READ-ONLY',
    indexHealthy: 'Index healthy',
    live: 'LIVE',
    signOut: 'Sign out',
    account: 'Account',
    openAccount: 'Open account menu',
    session: 'Session',
    readOnlyOperator: 'Read-only operator',
    localDemo: 'admin / local demo',
    defiIntelligence: 'DeFi intelligence',
  },
  overview: {
    eyebrow: 'Aave V3 / Ethereum',
    title: 'Protocol pulse',
    lastSynced: 'Last synced',
    markets: 'markets',
    totalSupplied: 'Total supplied',
    totalSuppliedDetail: 'Protocol liquidity supplied',
    totalBorrowed: 'Total borrowed',
    totalBorrowedDetail: 'Total variable debt',
    available: 'Available',
    availableDetail: 'Available liquidity',
    utilization: 'Utilization',
    utilizationDetail: 'Protocol utilization rate',
    marketMap: 'Market map',
    coreMarkets: 'Core reserve markets',
    supplied: 'supplied',
    dataPipeline: 'Data pipeline',
    syncSignal: 'Sync signal',
    pipelineHealthy: 'Data pipeline healthy',
    waitingForSync: 'Waiting for sync history',
    writtenMarkets: 'written markets',
    runFirstSync: 'Run the first sync to populate status.',
    latestRun: 'Latest run',
    dataSource: 'Data source',
    syncUpdated: 'Sync complete. Protocol data is up to date.',
    errorTitle: 'Unable to read protocol data',
  },
  reserves: {
    eyebrow: 'Reserve directory',
    title: 'Reserve markets',
    description: 'Compare liquidity, capital efficiency, and borrowing costs.',
    marketCount: 'markets',
    searchPlaceholder: 'Search asset symbol',
    searchLabel: 'Search asset symbol',
    sortLabel: 'Sort markets',
    sortSupplied: 'Sort by supplied',
    sortBorrowed: 'Sort by borrowed',
    sortUtilization: 'Sort by utilization',
    sortSupplyApy: 'Sort by supply APY',
    asset: 'Asset',
    supplied: 'Supplied',
    borrowed: 'Borrowed',
    available: 'Available',
    utilization: 'Utilization',
    supplyApy: 'Supply APY',
    borrowApy: 'Borrow APY',
    noMatches: 'No reserve markets match your search.',
    dataError: 'Unable to load reserve markets.',
  },
  detail: {
    backToMarkets: 'Back to reserve markets',
    description: 'Ethereum Mainnet · Current reserve state and historical series',
    demoAsset: 'Demo asset',
    indexedAsset: 'Indexed asset',
    network: 'Ethereum / AAVE V3',
    totalSupplied: 'Total supplied',
    totalBorrowed: 'Total borrowed',
    utilization: 'Utilization',
    supplyBorrowApy: 'Supply / borrow APY',
    historicalSeries: 'Historical series',
    liquidityTitle: 'Supply and borrow volume',
    ratesTitle: 'Supply and borrow APY',
    liquidity: 'Liquidity',
    rates: 'Rates',
    suppliedVolume: 'Supply volume',
    borrowedVolume: 'Borrow volume',
    suppliedApy: 'Supply APY',
    borrowedApy: 'Borrow APY',
    points: 'points',
    chartFooter: 'Charting by TradingView · Read-only research and demo data',
    trendError: 'Unable to load historical series.',
    apyChartLabel: 'APY history chart',
    liquidityChartLabel: 'Supply and borrow history chart',
  },
  sync: {
    eyebrow: 'Data pipeline',
    title: 'Sync runs',
    description: 'Every batch records its source, duration, writes, and error summary.',
    latestSource: 'Latest source',
    lastStatus: 'Last status',
    written: 'Written',
    dataSource: 'Data source',
    recentStatus: 'Recent status',
    writtenMarkets: 'markets written',
    executionHistory: 'Execution history',
    pipelineRuns: 'Pipeline runs',
    noRuns: 'No sync runs yet.',
    dataError: 'Unable to load sync history.',
    read: 'Read',
    write: 'Write',
    syncComplete: 'Sync complete. A new run has been recorded.',
    syncFailed: 'Sync failed.',
  },
} as const

const statusLabels: Record<string, string> = {
  succeeded: 'Succeeded',
  failed: 'Failed',
  running: 'Running',
  pending: 'Pending',
  idle: 'Idle',
}

export function statusLabel(status: string): string {
  return statusLabels[status.toLowerCase()] || 'Unknown'
}

export function sourceLabel(source: string): string {
  if (source.toLowerCase() === 'demo') return 'Demo index'
  if (source.toLowerCase() === 'graph') return 'The Graph'
  return 'External index'
}

export function errorMessage(cause: unknown, fallback: string): string {
  if (import.meta.env.DEV && cause instanceof Error) console.error(cause)
  if (typeof cause === 'object' && cause !== null && 'status' in cause && cause.status === 401) {
    return copy.auth.invalidCredentials
  }
  return fallback
}
